//
//  RichToHTMLFragmentTests.swift
//  DrPasteTests
//
//  Rich → HTML must emit a content FRAGMENT, not Cocoa's full document with
//  DOCTYPE / <head> / <style> boilerplate — you paste a snippet into existing
//  HTML, not a whole page.
//

import XCTest
import AppKit
@testable import DrPaste

final class RichToHTMLFragmentTests: XCTestCase {

    func testHTMLExportStripsDocumentBoilerplate() throws {
        let attr = NSMutableAttributedString(
            string: "Hello",
            attributes: [.font: NSFont.boldSystemFont(ofSize: 13)])
        attr.append(NSAttributedString(string: " world"))

        let html = try XCTUnwrap(RichTextHelpers.attributedStringToHTML(attr))

        // No document chrome.
        XCTAssertFalse(html.localizedCaseInsensitiveContains("<!DOCTYPE"), "DOCTYPE leaked: \(html)")
        XCTAssertFalse(html.localizedCaseInsensitiveContains("<head"), "head leaked: \(html)")
        XCTAssertFalse(html.localizedCaseInsensitiveContains("<body"), "body tag leaked: \(html)")
        XCTAssertFalse(html.localizedCaseInsensitiveContains("Cocoa HTML Writer"), "generator meta leaked: \(html)")
        XCTAssertFalse(html.contains("class=\"p1\""), "autogenerated style class leaked: \(html)")
        // Content survives.
        XCTAssertTrue(html.contains("Hello"), "content lost: \(html)")
        XCTAssertTrue(html.contains("world"), "content lost: \(html)")
    }
}
